### ISSUE TITLE
Wondering about the perfdata on the pg_dump_backup service

### ISSUE THREAD

**Issue by gleu** [OPMDG/check_pgactivity#101]
Not sure if this is a bug or not.

When I use the pg_dump_backup service and when the delta is beyond the warning and/or critical values, it gives me the size of the latest backup in the perfdatas. It looks like this:

POSTGRES_PGDUMP_BACKUP CRITICAL: 'b1_delta'=2301687B

From the name of the label, I thought it was the size of the delta for my b1 database. But actually, it is the size of the latest backup. Shouldn't it be the size of the delta?

**Comment by frost242** [comment]
Sorry for the delay. 

The delta perfdata is calculated this way : 
@perf_delta  = exists $db_sizes{$db} ?
  ( "${db}_delta",  $lasts{$db}[1] - $db_sizes{$db}[1], 'B' )
  : ( "${db}_delta", 0, 'B' );

db_sizes holds the size of a dump as detected since last call. lasts holds the current dump size.

Was your first backup empty or anything ? Were you running this service for the first time ever ? At first look, you should not get this kind of message in this second case. I'll take a further look on monday.

Thanks for the report

**Comment by frost242** [comment]
Hi,

Sorry again for the big delay regarding this issue. I guess you encountered the case I explained: this service was probably run for the first time ever.

The delata perfdata is correctly calculated in other cases.

Please, reopen the issue if you have a test case.

Thanks for the report
