### ISSUE TITLE
"insufficient privilege" for non-superuser

### ISSUE THREAD

**Issue by loukash** [OPMDG/check_pgactivity#110]
How I can get a real backend status for non-superuser?
Can you replace "SELECT * FROM pg_stat_activity" to "SELECT * FROM pg_stat_activity()"?

```
CREATE OR REPLACE FUNCTION public.pg_stat_activity() RETURNS SETOF pg_catalog.pg_stat_activity
AS $BODY$
DECLARE
 rec RECORD;
BEGIN
    -- Author: Tony Wasson (part of nagiosplugins for postgresql)
    -- Overview: Let non super users see query details from pg_stat_activity
    -- Revisions: (when, who, what)
    --   2006-08-29 TW - Checked into CVS after a user request.
    FOR rec IN SELECT * FROM pg_stat_activity
    LOOP
        RETURN NEXT rec;
    END LOOP;
    RETURN;
END;
$BODY$ LANGUAGE plpgsql SECURITY DEFINER;
```
Do you have any solution?

**Comment by rjuju** [comment]
Hello,

This problem will be solved in postgres 10, see https://www.postgresql.org/docs/10/static/default-roles.html and the new "pg_read_all_stats" default role.

In the meantime, check_pgactivity aim is to be usable with minimal impact on the monitored server, therefore we can't force people to create an SRF for this :(

If you can't or don't want to use a superuser for this (which I BTW totally agree with), you just need minimal additional steps to the pg_stat_activity() function you mention:

* create a dedicated schema, let's say "monitoring"
* create a monitoring.pg_stat_activity view that returns a plain select * from pg_stat_activity() (you may want to create this function in the dedicated schema)
* specificy this schema before pg_catalog schema in the default seach_path of your monitoring user(s)

For instance, assuming you'll use **monitor** role and **monitoring** schema:
```sql
CREATE USER monitor LOGIN NOSUPERUSER;
CREATE SCHEMA monitoring;
GRANT USAGE ON monitoring TO monitor;
CREATE VIEW monitoring.pg_stat_activity AS SELECT * FROM public.pg_stat_activity();
GRANT SELECT ON monitoring.pg_stat_activity TO monitor;
ALTER ROLE monitor SET search_path = monitoring, pg_catalog,"$user", public;
```
**WARNING**

Please note that there's an issue in the **pg_stat_activity()** function you provided, because it's not using fully qualified relation name.  The **FOR rec** line should be

```sql
FOR rec IN SELECT * FROM pg_catalog.pg_stat_activity
```

After that, everything should work if you configure check_pgactivity to use the **monitor** role.  I agree that's far from ideal, but in a few years pg10+ versions should be wildly used :)

**Comment by frost242** [comment]
Hello,

As an addition, I once developped an extension called monitoring_role that helps using a non-superuser role for monitoring. However, this extension is provided as is and is not part of check_pgactivity.

As Julien outlined in his previous reply, Postgres 10 will provide such feature. The current development branch of check_pgactivity has already every required changes to support it.
