### ISSUE TITLE
Should oldest_idlexact check the oldest idle transaction, or the time since the idle transaction is idle?

### ISSUE THREAD

**Issue by maethor** [OPMDG/check_pgactivity#131]
A transaction can take some time to build up, not being idle. Then, the transaction idles, and the check immediately returns a one or two minute idle… but the transaction is really idle for a couple of seconds.

I believe the doc should be clarified, or the probe should check the real idle time, and not the age of idle transactions.

What do you think?

**Comment by frost242** [comment]
Hello,

I need to think further on this issue. However, this held another issue: a very long-running transaction can be very problematic, in the same way as an idle transaction. It simply blocks the VACUUM process and prevents the dead tuples being marked as reusable.

The aim of this service is to alert if a transaction is idling for several minutes or hours. This kind of transaction is often due to an application bug or, in some cases, a crashed client.

**Comment by maethor** [comment]
Hello,

Indeed, the current action is useful too. Maybe it's not enough clear for me then. Because "Idle" means… well, idle, not running :) Maybe it needs two different actions.

What thresholds would you recommend for the current `oldest_idlexact` action?

**Comment by frost242** [comment]
Hello,
Yes, we have to think about it.

The thresholds will depend on your context. You'll get answer by answering this question : what is the duration of your longest transaction on your database ? Take also the duration of a pg_dump into account.

For the first question, add one hour or two in order to avoid receiving alerts because you simply have a simple slowdown. We usually set the warning threshold to one hour, and critical to two hours, this is usually OK for small to medium instances. We adjust the thresholds higher on bigger PostgreSQL instances.

I hope this answers your question.

**Comment by maethor** [comment]
OK, thank you!

So my 1 minute warning and 5 minutes critical may be a bit too extreme :smile:

**Comment by frost242** [comment]
Yes, sure !

**Comment by frost242** [comment]
Can I close this issue ?

**Comment by maethor** [comment]
Yes, thank you.
