### ISSUE TITLE
Allow replication_slots service on standby

### ISSUE THREAD

**Issue by anayrat** [OPMDG/check_pgactivity#203]
Hello,

I notice we cannot use `replication_slots` on a standby : 
```
ERROR:  recovery is in progress
HINT:  pg_xlogfile_name_offset() cannot be executed during recovery.
```
pg_xlogfile_name_offset() can only be executed only on a primary:

- [pg_xlogfile_name_offset() et al and recovery](https://www.postgresql.org/message-id/flat/b1d81f71-faf6-5fa2-b647-aa9097f94428%40lab.ntt.co.jp#c194dc50486209a4c2405ec74a58c679)
- [Forbid using pg_xlogfile_name() and pg_xlogfile_name_offset() during](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=370f770c15a4c08094298685)

I will try to found a workaround.

Regards,

**Comment by anayrat** [comment]
Hi,
I worked on this issue and I wonder if `- (pg_xlogfile_name_offset(restart_lsn)).file_offset` is really useful. I'm wondering if there is an error here : 

```SQL
floor(
                (pg_xlog_location_diff(
                     CASE WHEN pg_is_in_recovery() THEN pg_last_xlog_receive_location()
                          ELSE pg_current_xlog_location()
                      END
		, slot.restart_lsn)
                - (pg_xlogfile_name_offset(restart_lsn)).file_offset
                )
                / (s.val)
            )
```

With a draw : 
```
              restart_lsn                        current_lsn
                  +                                   +
                  |        pg_xlog_location_diff      |
+-----------------+-----------------------------------+------>

        +-------------------+
        |       WAL         |
        +-------------------+

        <--------->
        file_offset

```
I think, first goal is to **add** file_offset to not miss first wal keeped? I wonder if it is really needed to have a such precision for just one wal while we have a floor after this compute?

I made few tests, without floor with + or - file_offset : 
With a secondary without significant lag : 
  * `-file_offset` : replslot_wal_keep = -0.654
  * `+file_offset` : replslot_wal_keep = 0.654
 * without `file_offset` : replslot_wal_keep = 0.00002670

With floor : 
  * `-file_offset` : replslot_wal_keep = -1
  * `+file_offset` : replslot_wal_keep = 0

Thanks
  * without `file_offset` : replslot_wal_keep = 0

**Comment by rjuju** [comment]
@anayrat Indeed, there's a problem with ` - (pg_xlogfile_name_offset(restart_lsn)).file_offset`.  It should be a `+`

This is required for logical replication slots to avoid a possible off by one problem, since they report a partial WAL location.

For instance, if your logical replication slot is disconnected at 15.9 MB of a WAL, and 200 kB is written.  The location diff will obviously report 200 kB, but we still need to report that a whole WAL is retained.

So, unless we find a way to get the same information (basically the LSN of the begingning of the underlying WAL file), I don't think that we can support this probe on a standby.

I'll go and fix the operation error anyway.

**Comment by ioguix** [comment]
@rjuju If I understand correctly what you wrote in #241, this issue should be closed, thanks to your commit 014da279326, isn't it? Do I miss something?

**Comment by rjuju** [comment]
Well, according to #241 https://github.com/OPMDG/check_pgactivity/commit/014da27932686459ca3fdccf01acf6fc206f94bd didn't entirely fix the issue.  I didn't try to reproduce it, so for now I'm not sure what's the root cause.

For this issue, the problem is ability to use this check on a standby.  We could make it work, but then we'd have a possible off-by-one fuzz, either optimistic or pessimistic.  I'm not opposed to that as it's probably better to have a check even if it's there's some blur, but we should make it quite clear in the documentation that this flaw exists.

**Comment by anayrat** [comment]
+1

**Comment by ioguix** [comment]
OK, so the discussion in this issue slightly shift out of topic. The off-by-one fuzz issue is covered by #241. Let's not focus on this here. Let's focus only on standby support.

The only function not available in recovery that could not be replaced by something else seems to be  `pg_walfile_name_offset().file_offset`, and this one could be replaced with:

~~~
pg_wal_lsn_diff(pg_current_wal_lsn(), '0/0')%s.wal_segment_size
~~~

I'll wrap a patch a we'll discuss in the PR.

**Comment by rjuju** [comment]
No, the off-by-one issue I'm talking about is the one explained in

> For instance, if your logical replication slot is disconnected at 15.9 MB of a WAL, and 200 kB is written. The location diff will obviously report 200 kB, but we still need to report that a whole WAL is retained.

Without the use of pg_xlogfile_name_offset(), you willingly add an off-by-one hazard.  With your example, the result has to be read "either the number returned of the number +1, we don't know".

**Comment by ioguix** [comment]
> With your example, the result has to be read "either the number returned of the number +1, we don't know".

I don't get it. My example is computationally the same than `pg_xlogfile_name_offset()`. The only difference is (from `src/backend/access/transam/xlogfuncs.c:pg_walfile_name_offset()`):

~~~C
/* [...]
 * Note that a location exactly at a segment boundary is taken to be in
 * the previous segment.  This is usually the right thing, since the
 * expected usage is to determine which xlog file(s) are ready to archive.
 */
~~~

And there was in fact a discussion back in July about this on pgsql-hackers. See https://www.postgresql.org/message-id/flat/20190726.172120.101752680.horikyota.ntt%40gmail.com

**Comment by rjuju** [comment]
Ah you're right, sorry for the noise!

**Comment by anayrat** [comment]
Thanks!
