### ISSUE TITLE
Lack of maintenance not detected

### ISSUE THREAD

**Issue by rjuju** [OPMDG/check_pgactivity#249]
Looking at `check_last_maintenance`, I see that the code fails to properly account for tables that were never vacuumed or analyzed, which can lead to a "OK" result if that's the state of all the tables

To be more accurate, there's a coalesce to `NaN`, but the verification is done using `-inf`
(see https://github.com/OPMDG/check_pgactivity/blob/master/check_pgactivity#L4547 and https://github.com/OPMDG/check_pgactivity/blob/master/check_pgactivity#L4612)

**Comment by frost242** [comment]
@rjuju the MIN() aggregate is also a problem to this issue. It does not take account of NULL values, so the only way you'll get a NaN is when there was no maintenance at all on the database.

**Comment by frost242** [comment]
Anyone has a chance to take a look at my PR ?

**Comment by Krysztophe** [comment]
Hi,

I've tested it, and it seems okay. Once a single simple unvacuumed table is added, I get a CRITICAL:
`POSTGRES_LAST_ANALYZE CRITICAL: pogo: -Infinity | banque=12311.288849s;86400;432000 christ=NaNs;86400;436400;432000 icingaweb=12346s;86400;432000 owncloud=12294.675267s;86400;432000 pgbench=12294.198117s;86400;432000 pogo=-Infinitys;;86400;432000`

The critical disapears after a VACUUM resp. ANALYZE. 
The unvacuumed/unanalyzed table raises the critical when other vacuumed tables exist.
A database without any table does not raise a warning (the query gives NaN).

I'm just wondering if users will like the change in behaviour. If you add a single table for any reason, you immediately get a critical. This is not really the same thing as a autovacuum that is lacking behind. On the other side, you do have unvacuumed tables.

So that's okay for me.

**Comment by frost242** [comment]
Thanks, merged

**Comment by ioguix** [comment]
According to #256, this is issue fixed

**Comment by Krysztophe** [comment]
Reopening:  

with the new code,
when there are many temp tables, or the application like to create many tables, the result becomes CRITICAL / -Infinity because of all the empty last_analyze/last_autoanalyze. 

We can add `relpersistence = 't' ` for the temp tables, but it will not be enough. 

Adding `--exclude` may be another options.

But a very small table too small to have ever been analyzed will still trigger a CRITICAL.

(Same problem for vacuum, of course)

**Comment by ioguix** [comment]
> We can add `relpersistence = 't'` for the temp tables, 

This is only for 9.1+. Matching on `pg_temp_*` and `pg_toast_temp_*` is fine.

> but it will not be enough.

Why?

> Adding --exclude may be another option

Might be, maybe in 2.6 then. Adding `--exclude`/`--include` is easy to do and useful on its own, but we have to think more about the temps tables situation anyway. I don't want to postpone the release again and again and again.

> But a very small table too small to have ever been analyzed will still trigger a CRITICAL

This service spirit is to check if periodic global maintenance succeed eg. during the night.

See PR #278

**Comment by ioguix** [comment]
I'm closing this one for release 2.5.

I will open a new one to discuss about lack of maintenance on temp table for 2.6.
