### ISSUE TITLE
enhance the uptime check to check for database not being restarted after a given delay.

### ISSUE THREAD

**Issue by frost242** [OPMDG/check_pgactivity#281]
Hello,

At my workplace, we have an unusual use case with the uptime check.

We want to ensure that every database are restarted once a week (pg_prewarm saves our butt and this permits configuration changes). We wanted to use the uptime check but this one works in the opposite way, to detect if the database was restarted during a certain period of time, which is of course very interesting.
Would you accept a patch to accept negative delays for the uptime, in order to verify that the database was restarted for less than a given delay ?
Another way to make this check for us it to use a custom query, which is OK too.

Let me know please.

Kind regards

**Comment by Krysztophe** [comment]
In any case, you should be able to define both, to raise a warning if the DB if up for LESS than 10 min or MORE than 6 months.

Something like  -c 'min=10m,max=180d' ... but the min/max may names are confusing.

I use 6 months as an example, because that could be an indication that a minor release should be applied (but we have a service for that). But 1 week, seriously?

**Comment by frost242** [comment]
I know. Each database is restarted once a week. I would have prefered a longer delay but now we have to rely on pg_prewarm to refill our caches.

**Comment by frost242** [comment]
Btw, thanks for the feedback. I'll see what I can do and how, your proposal is good.

**Comment by ioguix** [comment]
Hi,

Should we keep this open ?

**Comment by frost242** [comment]
We can close it. I'll push something ASAP
