### ISSUE TITLE
check_backup_label_age fails with PostgreSQL 15

### ISSUE THREAD

**Issue by frost242** [OPMDG/check_pgactivity#334]
Hello,

As the exclusive backup mode has been removed in PostgreSQL 15, check_backup_label_age fails with an error because function pg_is_in_backup() has been removed.

As we have templates that apply to PostgreSQL monitoring with no distinction on PostgreSQL release, the best way for my use case to handle this is to return OK. But I guess it would be better to return UNKNOWN.

I'll provide a patch to return UNKNOWN for PostgreSQL 15+ for this check. Let me know if you prefer OK.

Regards

**Comment by ioguix** [comment]
Starting with 9.6, the `pg_stat_file` function accept `missing_ok` as second argument to returns `NULL` if the file missing instead of erroring out. However, it would requires superuser privileges. But starting with v12 `pg_stat_file` execution is granted to any role granted to the pg_monitor role, which some other services are requiring anyway.

Checking the `backup_label` file might still be useful to make sure such file has not been kept around after a PITR restore because of an old script bug inherited from older versions or some human mistake.

So, what about using the following query starting from v12 ?

~~~sql
SELECT coalesce(extract(epoch from now() - modification), 0)
FROM pg_stat_file('backup_label', true);
~~~

**Comment by frost242** [comment]
Looks good. I'll provide a patch next week.

**Comment by frost242** [comment]
Fix committed. Tested in production.
