### ISSUE TITLE
Avoid duplicated performance measures

### ISSUE THREAD

**Issue by isaiasanchez** [OPMDG/check_pgactivity#51]
We use Grafana to display the perf measures in a dashboard, but it's difficult when we have a service with duplicated labels. For example temp_files, each database have 4 perf measures with the same label, database name.

I think would be great to add a sufix (or prefix) to the database name indicating the kind of measueres. 

For example:
postgres_Fpm=0Fpm postgres_Bpm=0Bpm postgres_temp_files=0Files postgres_temp_size=0B

Instead of:
postgres=0Fpm postgres=0Bpm postgres=0Files postgres=0B

The longest_query service use something like I am explaining

**Comment by rjuju** [comment]
Hi,

Couldn't this be handled / configured in grafana? Like perhaps display a hover hint with the unit or something.

The problem is that the perfdata size is limited (4k in standard nagios), and having lot of database would raise an issue sooner. It would also make graphs less readable in OPM UI.

If it cannot be solved in grafana, I think we could do this with a new `--format` type.
