### ISSUE TITLE
Please provide Define Command & All Service example to setup in OPM UI.

### ISSUE THREAD

**Issue by yashvekaria** [OPMDG/check_pgactivity#70]

**Comment by rjuju** [comment]
Hi,

I'm not sure I understand your question.  OPM UI will display whatever data is returned by nagios.

Do you need help to setup OPM UI or to configure check_pgactivity in Nagios? Or do you have any specific issue?

**Comment by gauravsoni1992** [comment]
Hello rjuju,

i want to configure check_pgactivity in Nagios. For that please guide me step by step with command & service.

Thanks

**Comment by rjuju** [comment]
The problem is that it's more a Nagios problem than an OPM problem.  OPM is heavily based on Nagios, so you shouldn't consider setting up OPM if you don't have any knowledge of Nagios and don't want to learn how to configure it.  Also, this question has already been asked multiple time, and the answer is always the same: we can't provide detailed steps to setup commands and service, since it depends on how you can and want to access to the monitored servers.  For instance, you should start by deciding if you want to use check by ssh, NRPE or distant checks.  The Nagios documentation is quite good though, so it shouldn't be a problem.  If you encounter specific problem, we can try to help you but we're just Nagios users, not Nagios expert.

**Comment by gauravsoni1992** [comment]
Thank you
